server:
  port: 8083

spring:
  application:
    name: approval-processing-service

grpc:
  server:
    port: 9091
  client:
    approval-request-service:
      address: static://localhost:9090
      negotiation-type: plaintext

logging:
  level:
    com.erp.processing: DEBUG
