server:
  port: 8080

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.erp.notification.kafka.ApprovalNotificationEvent

kafka:
  topic:
    notification: approval-notification

logging:
  level:
    com.erp.notification: DEBUG
